spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
cwa-testresult-server:
  host: ${TESTRESULT_SERVER_HOST}
  port: ${TESTRESULT_SERVER_PORT}
  url: "${cwa-testresult-server.host}:${cwa-testresult-server.port}"
jwt:
  host: ${IAM_VERIFICATION_HOST}
  port: ${IAM_VERIFICATION_PORT}
  server: "${jwt.host}:${jwt.port}"
